from unittest.mock import MagicMock, patch

import pytest


def _result(returncode=0, stdout="", stderr=""):
    r = MagicMock()
    r.returncode = returncode
    r.stdout = stdout
    r.stderr = stderr
    return r


def _imap_ok(mock_imap):
    instance = MagicMock()
    instance.__enter__.return_value = instance
    mock_imap.return_value = instance
    return instance


def _imap_fail(mock_imap):
    import imaplib
    instance = MagicMock()
    instance.__enter__.return_value = instance
    instance.login.side_effect = imaplib.IMAP4.error("LOGIN failed")
    mock_imap.return_value = instance
    return instance


def _auth_header(user="alice", password="pw"):  # NOSONAR — test fixture, not a real credential
    return {"Authentication": f"{user}:{password}"}


URL = "/api/alias/random/new"


class TestCreateRandomAlias:
    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_success_with_hostname(self, mock_imap, mock_run, client):
        _imap_ok(mock_imap)
        mock_run.side_effect = [_result(stdout=""), _result()]
        resp = client.post(
            URL + "?hostname=www.netflix.com",
            headers=_auth_header(),
            json={"note": "Generated by Bitwarden"},
        )
        assert resp.status_code == 201
        data = resp.get_json()
        assert "alias" in data
        assert data["alias"].endswith("-netflix@example.com")
        assert data["alias"].startswith("g-")

    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_success_without_hostname(self, mock_imap, mock_run, client):
        _imap_ok(mock_imap)
        mock_run.side_effect = [_result(stdout=""), _result()]
        resp = client.post(URL, headers=_auth_header())
        assert resp.status_code == 201
        alias = resp.get_json()["alias"]
        # Unlabeled: g-<8hex>@domain  (no '-' after the random)
        local = alias.split("@", 1)[0]
        assert local.startswith("g-")
        assert "-" not in local[2:]  # no extra hyphen after "g-"

    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_returns_only_alias_field(self, mock_imap, mock_run, client):
        _imap_ok(mock_imap)
        mock_run.side_effect = [_result(stdout=""), _result()]
        resp = client.post(URL, headers=_auth_header())
        assert set(resp.get_json().keys()) == {"alias"}

    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_collision_retries(self, mock_imap, mock_run, client):
        _imap_ok(mock_imap)
        # First list returns one existing alias; add should still succeed because
        # we'll generate a different random prefix anyway (collision is astronomical)
        existing = "* g-deadbeef@example.com alice@example.com\n"
        mock_run.side_effect = [_result(stdout=existing), _result()]
        resp = client.post(URL, headers=_auth_header())
        assert resp.status_code == 201

    def test_missing_authentication_header(self, client):
        resp = client.post(URL)
        assert resp.status_code == 401
        assert resp.get_json() == {"error": "authentication required"}

    def test_malformed_authentication_header(self, client):
        resp = client.post(URL, headers={"Authentication": "no-colon-here"})
        assert resp.status_code == 401

    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_auth_header_strips_whitespace_and_bearer(self, mock_imap, mock_run, client):
        instance = _imap_ok(mock_imap)
        mock_run.side_effect = [_result(stdout=""), _result()]
        resp = client.post(
            URL,
            headers={"Authentication": "  Bearer alice:pw  "},  # NOSONAR — test fixture
        )
        assert resp.status_code == 201
        instance.login.assert_called_once_with("alice@example.com", "pw")

    def test_parse_authentication_header_helpers(self):
        from app.api import _parse_authentication_header
        assert _parse_authentication_header("alice:pw") == ("alice", "pw")
        assert _parse_authentication_header("  Bearer alice:pw\n") == ("alice", "pw")
        assert _parse_authentication_header("alice:") is None
        assert _parse_authentication_header("no-colon") is None

    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_bad_password(self, mock_imap, client):
        _imap_fail(mock_imap)
        resp = client.post(URL, headers=_auth_header(password="wrong"))  # NOSONAR — test fixture, not a real credential
        assert resp.status_code == 401

    def test_denied_user(self, client):
        # gitea is in GUISE_DENIED_USERS (set in conftest); never reaches IMAP
        resp = client.post(URL, headers=_auth_header(user="gitea"))
        assert resp.status_code == 401

    def test_invalid_username(self, client):
        resp = client.post(URL, headers={"Authentication": "Alice:pw"})
        # uppercase fails USERNAME_RE; never reaches IMAP
        assert resp.status_code == 401

    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_full_email_in_auth_header(self, mock_imap, mock_run, client):
        instance = _imap_ok(mock_imap)
        mock_run.side_effect = [_result(stdout=""), _result()]
        resp = client.post(
            URL, headers=_auth_header(user="alice@example.com"),
        )
        assert resp.status_code == 201
        instance.login.assert_called_once_with("alice@example.com", "pw")
        # Alias still targets short-local@GUISE_DOMAIN
        add_args = mock_run.call_args_list[1].args
        assert add_args[1:3] == ("alias", "add")
        assert add_args[4] == "alice@example.com"

    def test_unknown_domain_in_auth_header(self, client):
        resp = client.post(
            URL, headers=_auth_header(user="alice@evil.com"),
        )
        assert resp.status_code == 401

    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_allowlisted_alternate_domain_in_auth_header(
        self, mock_imap, mock_run, monkeypatch, tmp_path,
    ):
        monkeypatch.setenv("GUISE_DOMAIN", "example.com")
        monkeypatch.setenv("GUISE_ALLOWED_DOMAINS", "other.com")
        monkeypatch.setenv("GUISE_DENIED_USERS", "")
        monkeypatch.setenv("DATA_DIR", str(tmp_path))
        monkeypatch.setenv("SESSION_COOKIE_SECURE", "0")
        from app import create_app
        app2 = create_app()
        app2.config["TESTING"] = True
        c2 = app2.test_client()
        instance = _imap_ok(mock_imap)
        mock_run.side_effect = [_result(stdout=""), _result()]
        resp = c2.post(URL, headers=_auth_header(user="alice@other.com"))
        assert resp.status_code == 201
        instance.login.assert_called_once_with("alice@other.com", "pw")

    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_csrf_not_enforced_on_api(self, mock_imap, mock_run, client):
        # No CSRF cookie, no CSRF token — would 400 on /create but must succeed here
        _imap_ok(mock_imap)
        mock_run.side_effect = [_result(stdout=""), _result()]
        resp = client.post(URL, headers=_auth_header())
        assert resp.status_code == 201

    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_list_failure(self, mock_imap, mock_run, client):
        _imap_ok(mock_imap)
        mock_run.return_value = _result(returncode=1, stderr="docker unhappy")
        resp = client.post(URL, headers=_auth_header())
        assert resp.status_code == 500
        assert "list" in resp.get_json()["error"]

    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_add_failure(self, mock_imap, mock_run, client):
        _imap_ok(mock_imap)
        mock_run.side_effect = [
            _result(stdout=""),
            _result(returncode=1, stderr="alias add failed"),
        ]
        resp = client.post(URL, headers=_auth_header())
        assert resp.status_code == 500

    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_autolabel_disabled_via_config(
        self, mock_imap, mock_run, monkeypatch, tmp_path
    ):
        monkeypatch.setenv("GUISE_DOMAIN", "example.com")
        monkeypatch.setenv("GUISE_DENIED_USERS", "")
        monkeypatch.setenv("DATA_DIR", str(tmp_path))
        monkeypatch.setenv("GUISE_API_AUTOLABEL", "0")
        from app import create_app
        app2 = create_app()
        app2.config["TESTING"] = True
        c2 = app2.test_client()
        _imap_ok(mock_imap)
        mock_run.side_effect = [_result(stdout=""), _result()]
        resp = c2.post(URL + "?hostname=www.netflix.com", headers=_auth_header())
        assert resp.status_code == 201
        local = resp.get_json()["alias"].split("@", 1)[0]
        # No label appended even though hostname was sent
        assert "-netflix" not in local

    @patch("app.aliases._run_setup")
    @patch("app.auth.imaplib.IMAP4_SSL")
    def test_logs_via_api_marker(self, mock_imap, mock_run, client, caplog):
        import logging
        _imap_ok(mock_imap)
        mock_run.side_effect = [_result(stdout=""), _result()]
        with caplog.at_level(logging.INFO):
            client.post(
                URL + "?hostname=netflix.com",
                headers=_auth_header(),
                json={"note": "test-note"},
            )
        assert any("via=api" in r.message for r in caplog.records)
        assert any("slug=netflix" in r.message for r in caplog.records)
